---
title: "RchivalTag Package Tutorial"
subtitle: 'Package Teaser'

author:
- name: "Dr. Robert Bauer | Data Scientist & Fishery Biologist"
  affiliation: 1

address:
- code: 1
  address: Hawai'i Institute of Marine Biology, University of Hawai'i at Mānoa, Kāne'ohe, Hawai'i, United States of America
  email: rkbauer@hawaii.edu
  orcid: https://orcid.org/0000-0003-4224-8023
  
date: "February 10, 2020"
##bibliography: library.bib
tags: Archival Tagging data, Satellite tags, Wildlife Computers, LOTEK


output: 
  uswebr::html_uswds:
    number_sections: FALSE
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(RchivalTag)
```

```{r, collapse=TRUE, message=FALSE,echo=FALSE}
kmz_file <- system.file("example_files/15P1019-104659-1-GPE3.kmz",package="RchivalTag")
k1 <- get_geopos(kmz_file,verbose = F)
kmz_file2 <- system.file("example_files/15P0986-15P0986-2-GPE3.kmz",package="RchivalTag")
k2 <- get_geopos(kmz_file2,verbose = F)
k0 <- k3 <- rbind(k1,k2)

library(leaflet)
leaflet_geopos(k0,ID_label="DeployID",collapsedLayers = T)%>% addMiniMap(position="bottomleft")
```

```{r, collapse=TRUE, message=FALSE,echo=FALSE}
leaflet_geopos(k0,ID_label="DeployID",showSlideBar = T)

```


```{r,echo=FALSE}
library(dplyr)
gpe3_file <- system.file("example_files/15P1019-104659-1-GPE3.csv",package="RchivalTag")
tracks <- get_geopos(gpe3_file,verbose = F)
add <- tracks %>% select(DeployID,Ptt,Lat,Lon,date) %>% 
                  group_by(DeployID,Ptt,date) %>%
                  summarise(Lat=mean(Lat),Lon=mean(Lon)) %>%
                  mutate(datetime=RchivalTag:::.date2datetime(date))
add <- classify_DayTime(add) %>% select(-datetime)

ts_file <- system.file("example_files/104659-Series.csv",package="RchivalTag")
dat <- read_TS(ts_file)
ts_df2 <- add %>% select(-DeployID) %>% inner_join(dat,by=c("date","Ptt","DeployID"))

g <- ggboxplot_DepthTS_by_hour(ts_df2,ylim=c(0,100))
g
```
```{r,echo=FALSE, results='hide'}
library(oceanmap)
data(cmap)
plot_DepthTempTS_resampled(ts_df2,xlim = c("2016-08-10","2016-08-15"))
```


```{r,echo=FALSE}
dy_DepthTS(ts_df2, xlim = unique(ts_df2$date)[2:10], plot_DayTimePeriods = TRUE, doRangeSelector= TRUE)

```



